/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PostFeedback$Params as PostFeedback$Params } from './fn/feedback-controller/post-feedback';
export { postFeedback as postFeedback } from './fn/feedback-controller/post-feedback';
export type { GetFeedbacksByBookId$Params as GetFeedbacksByBookId$Params } from './fn/feedback-controller/get-feedbacks-by-book-id';
export { getFeedbacksByBookId as getFeedbacksByBookId } from './fn/feedback-controller/get-feedbacks-by-book-id';
export type { GetAllBooks$Params as GetAllBooks$Params } from './fn/book-controller/get-all-books';
export { getAllBooks as getAllBooks } from './fn/book-controller/get-all-books';
export type { SaveBook$Params as SaveBook$Params } from './fn/book-controller/save-book';
export { saveBook as saveBook } from './fn/book-controller/save-book';
export type { UpdateCover$Params as UpdateCover$Params } from './fn/book-controller/update-cover';
export { updateCover as updateCover } from './fn/book-controller/update-cover';
export type { BorrowBook$Params as BorrowBook$Params } from './fn/book-controller/borrow-book';
export { borrowBook as borrowBook } from './fn/book-controller/borrow-book';
export type { UpdateShareable$Params as UpdateShareable$Params } from './fn/book-controller/update-shareable';
export { updateShareable as updateShareable } from './fn/book-controller/update-shareable';
export type { ReturnBook$Params as ReturnBook$Params } from './fn/book-controller/return-book';
export { returnBook as returnBook } from './fn/book-controller/return-book';
export type { UpdateArchived$Params as UpdateArchived$Params } from './fn/book-controller/update-archived';
export { updateArchived as updateArchived } from './fn/book-controller/update-archived';
export type { ApproveReturnBook$Params as ApproveReturnBook$Params } from './fn/book-controller/approve-return-book';
export { approveReturnBook as approveReturnBook } from './fn/book-controller/approve-return-book';
export type { GetReturnedBooks$Params as GetReturnedBooks$Params } from './fn/book-controller/get-returned-books';
export { getReturnedBooks as getReturnedBooks } from './fn/book-controller/get-returned-books';
export type { GetBooksByOwner$Params as GetBooksByOwner$Params } from './fn/book-controller/get-books-by-owner';
export { getBooksByOwner as getBooksByOwner } from './fn/book-controller/get-books-by-owner';
export type { GetBorrowedBooks$Params as GetBorrowedBooks$Params } from './fn/book-controller/get-borrowed-books';
export { getBorrowedBooks as getBorrowedBooks } from './fn/book-controller/get-borrowed-books';
export type { FindBookById$Params as FindBookById$Params } from './fn/book-controller/find-book-by-id';
export { findBookById as findBookById } from './fn/book-controller/find-book-by-id';
export type { Register$Params as Register$Params } from './fn/auth-controller/register';
export { register as register } from './fn/auth-controller/register';
export type { Authentication$Params as Authentication$Params } from './fn/auth-controller/authentication';
export { authentication as authentication } from './fn/auth-controller/authentication';
export type { Confirm$Params as Confirm$Params } from './fn/auth-controller/confirm';
export { confirm as confirm } from './fn/auth-controller/confirm';
