/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthRequest } from './models/auth-request';
export type { AuthResponse } from './models/auth-response';
export type { BookHistoryResponse } from './models/book-history-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBookHistoryResponse } from './models/page-response-book-history-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { RegisterRequest } from './models/register-request';
