/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBookHistoryResponse } from '../../models/page-response-book-history-response';

export interface GetBorrowedBooks$Params {
  page?: number;
  size?: number;
}

export function getBorrowedBooks(http: HttpClient, rootUrl: string, params?: GetBorrowedBooks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBookHistoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getBorrowedBooks.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBookHistoryResponse>;
    })
  );
}

getBorrowedBooks.PATH = '/books/borrowed_books';
