/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookHistoryResponse {
  authorName?: string;
  id?: number;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  sbin?: string;
  title?: string;
}
