/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookHistoryResponse } from '../models/book-history-response';
export interface PageResponseBookHistoryResponse {
  content?: Array<BookHistoryResponse>;
  first?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
